name: CI Pipeline

on:
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Report
        run: |
          files=$(find "." -type f -name "*.md"  | wc -l | awk '{print $1}')
          if [ "$files" -gt 0 ]; then
            lines=$(find "." -type f -name "*.md"  -print0 | xargs -0 wc -l | tail -1 | awk '{print $1}')
            printf "%-10s %6s %8s\n" ".md" "$files" "$lines"
          fi

      - name: Run tests
        run: |
          npx playwright install --with-deps chromium
          npm run test:coverage

      - name: Update coverage
        run: |
          coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          color=$(echo "$coverage < 80" | bc | awk '{if ($1) print "red"; else print "green"}')
          curl -s -X POST "https://pizza-factory.cs329.click/api/badge/${{ secrets.NET_ID }}/jwtpizzacoverage?label=Coverage&value=$coverage%25&color=$color" -H "authorization: bearer ${{ secrets.FACTORY_API_KEY }}"